import { BrandStoreConfig } from "./types";

export const DEFAULT_TEMPLATE_CONFIG: BrandStoreConfig = {
  brandId: "partner-template",
  brandName: "YOUR BRAND",
  brandTagline: "Artisanal Denim & Tailored Essentials",
  brandStory:
    "This is a turnkey digital atelier built on OnlyDenims. Partner brands receive bespoke 3D garment visualization, custom branded aesthetics, direct mill manufacturing, and Gokwik 1-click checkout with pan-India delivery.",
  originCity: "Mumbai, India",
  foundedYear: "2026",
  accentColor: "#B9965A",
  accentHoverColor: "#9E7E45",
  badgeText: "PARTNER BRAND ATELIER • DEMO",
  isDemoMode: true,
  products: [
    {
      id: "raw-straight",
      name: "PURE RAW SELVEDGE",
      category: "jeans",
      washKey: "raw",
      tagline: "UNWASHED 14.5 OZ INDIGO",
      badge: "HERITAGE SIGNATURE",
      price: "₹ 1,950",
      compareAtPrice: "₹ 2,999",
      description:
        "Crafted on authentic shuttle looms using ring-spun long-staple cotton. Deep indigo warp designed to fade uniquely to the wearer's daily lifestyle.",
      fabricSpec: "14.5oz Pure Raw Indigo Selvedge Denim",
      fitSpec: "Straight Leg • Mid-High Rise • 5-Pocket Classic",
      careSpec: "Wear raw for 6 months before first cold soak; line dry inside out.",
      accentHex: "#C59B27",
      modelPath: "/raw.glb",
      images: [
        "/raw_jeans.png",
        "/preview_raw.png",
        "/rbw_lookbook1.png",
      ],
      sizes: ["28", "30", "32", "34", "36", "38", "40", "42"],
    },
    {
      id: "black-straight",
      name: "SULFUR OBSIDIAN SELVEDGE",
      category: "jeans",
      washKey: "black",
      tagline: "DOUBLE DYED JET BLACK",
      badge: "BESTSELLER",
      price: "₹ 1,950",
      compareAtPrice: "₹ 2,999",
      description:
        "Deep sulfur-dyed black warp and weft spun on vintage looms. Colorfast treatment ensures deep saturation with clean contrast stitching.",
      fabricSpec: "14.0oz Sulfur Black Selvedge Denim",
      fitSpec: "Loose / Straight Cut • Relaxed Thigh • Clean Break",
      careSpec: "Cold wash inside out with dark colors; line dry in shade.",
      accentHex: "#8B0015",
      modelPath: "/raw.glb",
      images: [
        "/black_jeans.png",
        "/preview_black.png",
        "/rbw_lookbook2.png",
      ],
      sizes: ["28", "30", "32", "34", "36", "38", "40", "42"],
    },
    {
      id: "white-straight",
      name: "ECRU NATURAL BULL DENIM",
      category: "jeans",
      washKey: "white",
      tagline: "UNBLEACHED TEXTURED WEAVE",
      badge: "LIMITED DROP",
      price: "₹ 1,950",
      compareAtPrice: "₹ 2,999",
      description:
        "Natural un-dyed ecru denim featuring visible organic cotton seed flecks and a soft yet heavyweight handle.",
      fabricSpec: "13.8oz Organic Ecru Bull Cotton Twill",
      fitSpec: "Straight Leg • Structured Silhouette",
      careSpec: "Gentle cold wash with like light tones; do not bleach.",
      accentHex: "#0A2A5E",
      modelPath: "/white.glb",
      images: [
        "/white_jeans.png",
        "/preview_white.png",
        "/rbw_lookbook1.png",
      ],
      sizes: ["28", "30", "32", "34", "36", "38", "40", "42"],
    },
  ],
};
