import { CarouselItemData } from "@/component/rbw/3d/RbwOrbitCarousel";

/**
 * Curated 3D showroom and atelier catalog for partner brand storefront template.
 * Each 3D jeans piece maps to a unique GLB model asset to prevent WebGL scene graph collisions.
 * All core washes feature full size runs (28-42) so size filtering never unintentionally drops items.
 */
export const TEMPLATE_SHOWROOM_ITEMS: CarouselItemData[] = [
  // ==============================================================
  // 1. ALL JEANS (Core Washes on Marble Pedestals)
  // ==============================================================
  {
    id: "jeans-raw",
    category: "jeans",
    type: "image",
    washKey: "raw",
    colorName: "Raw Indigo",
    colorHex: "#1E3A8A",
    availableSizes: ["28", "30", "32", "34", "36", "38", "40", "42"],
    fitType: "Straight",
    discountPct: 15,
    originalPrice: "₹2,299",
    name: "RAW",
    sublabel: "Zero Wash Rigid",
    tagline: "RAW YOU NEVER SAW",
    imagePath: "/rbwstore/raw.png",
    price: "₹1,950",
    accentHex: "#C59B27",
    textStyle: "text-raw-textured",
    btnText: "SHOP RAW JEANS →",
    btnBg: "bg-[#C59B27]",
    btnHover: "hover:bg-[#A8821B]",
    btnTextColor: "text-black",
    shopHref: "/stores/template?wash=raw",
    categoryBadge: "JEANS",
  },
  {
    id: "jeans-black",
    category: "jeans",
    type: "image",
    washKey: "black",
    colorName: "Sulfur Black",
    colorHex: "#18181B",
    availableSizes: ["28", "30", "32", "34", "36", "38", "40", "42"],
    fitType: "Baggy",
    discountPct: 20,
    originalPrice: "₹2,450",
    name: "BLACK",
    sublabel: "Sulfur Dyed Obsidian",
    tagline: "BOLD YOU NEVER KNEW",
    imagePath: "/rbwstore/black.png",
    price: "₹1,950",
    accentHex: "#8B0015",
    textStyle: "text-black-textured",
    btnText: "SHOP BLACK JEANS →",
    btnBg: "bg-[#8B0015]",
    btnHover: "hover:bg-[#660010]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?wash=black",
    categoryBadge: "JEANS",
  },
  {
    id: "jeans-white",
    category: "jeans",
    type: "image",
    washKey: "white",
    colorName: "Chalk White",
    colorHex: "#F5F5F0",
    availableSizes: ["28", "30", "32", "34", "36", "38", "40", "42"],
    fitType: "Bootcut",
    discountPct: 20,
    originalPrice: "₹2,500",
    name: "WHITE",
    sublabel: "Ecru Bull Denim",
    tagline: "WHITE YOU NEVER WORE",
    imagePath: "/rbwstore/white.png",
    price: "₹1,950",
    accentHex: "#0A2A5E",
    textStyle: "text-white-textured",
    btnText: "SHOP WHITE JEANS →",
    btnBg: "bg-[#0A2A5E]",
    btnHover: "hover:bg-[#061c40]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?wash=white",
    categoryBadge: "JEANS",
  },

  // ==============================================================
  // 2. ALL JACKETS (Outerwear)
  // ==============================================================
  {
    id: "jackets-raw",
    category: "jackets",
    type: "image",
    washKey: "raw",
    colorName: "Raw Indigo",
    colorHex: "#1E3A8A",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    fitType: "Comfort",
    discountPct: 15,
    originalPrice: "₹3,999",
    name: "RAW JACKET",
    sublabel: "14.5oz Rigid Selvedge",
    tagline: "14.5 OZ RIGID SELVEDGE TRUCKER",
    imagePath: "/raw_denim_jacket.png",
    price: "₹3,490",
    accentHex: "#C59B27",
    textStyle: "text-raw-textured",
    btnText: "SHOP RAW JACKET →",
    btnBg: "bg-[#C59B27]",
    btnHover: "hover:bg-[#A8821B]",
    btnTextColor: "text-black",
    shopHref: "/stores/template?wash=raw&category=jackets",
    categoryBadge: "JACKETS",
  },
  {
    id: "jackets-black",
    category: "jackets",
    type: "image",
    washKey: "black",
    colorName: "Jet Black",
    colorHex: "#18181B",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    fitType: "Slim",
    discountPct: 15,
    originalPrice: "₹4,100",
    name: "BLACK JACKET",
    sublabel: "Sulfur Jet Black",
    tagline: "14.0 OZ OVERSIZED OBSIDIAN TRUCKER",
    imagePath: "/black_denim_jacket.png",
    price: "₹3,490",
    accentHex: "#8B0015",
    textStyle: "text-black-textured",
    btnText: "SHOP BLACK JACKET →",
    btnBg: "bg-[#8B0015]",
    btnHover: "hover:bg-[#660010]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?wash=black&category=jackets",
    categoryBadge: "JACKETS",
  },
  {
    id: "jackets-vintage",
    category: "jackets",
    type: "image",
    washKey: "white",
    colorName: "Ecru Vintage Fade",
    colorHex: "#F5F5F0",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    fitType: "Comfort",
    discountPct: 20,
    originalPrice: "₹4,360",
    name: "WHITE JACKET",
    sublabel: "Ecru Workwear",
    tagline: "HAND-ABRADED ECRU BULL DENIM JACKET",
    imagePath: "/vintage_denim_jacket.png",
    price: "₹3,490",
    accentHex: "#0A2A5E",
    textStyle: "text-white-textured",
    btnText: "SHOP WHITE JACKET →",
    btnBg: "bg-[#0A2A5E]",
    btnHover: "hover:bg-[#061c40]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?wash=white&category=jackets",
    categoryBadge: "JACKETS",
  },

  // ==============================================================
  // 3. ALL SHORTS (Bottoms)
  // ==============================================================
  {
    id: "shorts-raw",
    category: "shorts",
    type: "image",
    washKey: "raw",
    colorName: "Raw Indigo",
    colorHex: "#1E3A8A",
    availableSizes: ["30", "32", "34", "36", "38", "40"],
    fitType: "Shorts",
    discountPct: 15,
    originalPrice: "₹1,750",
    name: "RAW SHORTS",
    sublabel: "Selvedge Hem",
    tagline: "RAW EDGED ATELIER BERMUDA SHORTS",
    imagePath: "/raw_denim_shorts.png",
    price: "₹1,490",
    accentHex: "#C59B27",
    textStyle: "text-raw-textured",
    btnText: "SHOP RAW SHORTS →",
    btnBg: "bg-[#C59B27]",
    btnHover: "hover:bg-[#A8821B]",
    btnTextColor: "text-black",
    shopHref: "/stores/template?wash=raw&category=shorts",
    categoryBadge: "SHORTS",
  },
  {
    id: "shorts-black",
    category: "shorts",
    type: "image",
    washKey: "black",
    colorName: "Jet Black",
    colorHex: "#18181B",
    availableSizes: ["30", "32", "34", "36", "38", "40"],
    fitType: "Shorts",
    discountPct: 15,
    originalPrice: "₹1,750",
    name: "BLACK SHORTS",
    sublabel: "Overdyed Obsidian",
    tagline: "OVERDYED OBSIDIAN UTILITY SHORTS",
    imagePath: "/black_denim_shorts.png",
    price: "₹1,490",
    accentHex: "#8B0015",
    textStyle: "text-black-textured",
    btnText: "SHOP BLACK SHORTS →",
    btnBg: "bg-[#8B0015]",
    btnHover: "hover:bg-[#660010]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?wash=black&category=shorts",
    categoryBadge: "SHORTS",
  },
  {
    id: "shorts-white",
    category: "shorts",
    type: "image",
    washKey: "white",
    colorName: "Chalk White",
    colorHex: "#F5F5F0",
    availableSizes: ["30", "32", "34", "36", "38", "40"],
    fitType: "Shorts",
    discountPct: 20,
    originalPrice: "₹1,860",
    name: "WHITE SHORTS",
    sublabel: "Ecru Canvas",
    tagline: "CRISP ECRU SUMMER RELAXED SHORTS",
    imagePath: "/white_denim_shorts.png",
    price: "₹1,490",
    accentHex: "#0A2A5E",
    textStyle: "text-white-textured",
    btnText: "SHOP WHITE SHORTS →",
    btnBg: "bg-[#0A2A5E]",
    btnHover: "hover:bg-[#061c40]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?wash=white&category=shorts",
    categoryBadge: "SHORTS",
  },

  // ==============================================================
  // 4. ACCESSORIES (Caps, Bags, Pouches)
  // ==============================================================
  {
    id: "acc-cap",
    category: "accessories",
    type: "image",
    washKey: "raw",
    colorName: "Indigo Selvedge",
    colorHex: "#1E3A8A",
    availableSizes: ["One Size"],
    fitType: "Straight",
    discountPct: 10,
    originalPrice: "₹1,100",
    name: "DENIM CAP",
    sublabel: "6-Panel Strapback",
    tagline: "100% COTTON RAW SELVEDGE 6-PANEL CAP",
    imagePath: "/rbw_cap.jpg",
    price: "₹990",
    accentHex: "#C59B27",
    textStyle: "text-raw-textured",
    btnText: "SHOP ACCESSORY →",
    btnBg: "bg-[#C59B27]",
    btnHover: "hover:bg-[#A8821B]",
    btnTextColor: "text-black",
    shopHref: "/stores/template?category=accessories",
    categoryBadge: "ACCESSORIES",
  },
  {
    id: "acc-tote",
    category: "accessories",
    type: "image",
    washKey: "black",
    colorName: "Heavyweight Canvas",
    colorHex: "#18181B",
    availableSizes: ["One Size"],
    fitType: "Comfort",
    discountPct: 15,
    originalPrice: "₹1,450",
    name: "TOTE BAG",
    sublabel: "Heavy Cotton Twill",
    tagline: "DAILY COMMUTER RAW SELVEDGE TOTE",
    imagePath: "/denim_tote_bag.jpg",
    price: "₹1,190",
    accentHex: "#8B0015",
    textStyle: "text-black-textured",
    btnText: "SHOP ACCESSORY →",
    btnBg: "bg-[#8B0015]",
    btnHover: "hover:bg-[#660010]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?category=accessories",
    categoryBadge: "ACCESSORIES",
  },
  {
    id: "acc-pouch",
    category: "accessories",
    type: "image",
    washKey: "white",
    colorName: "Natural Ecru",
    colorHex: "#F5F5F0",
    availableSizes: ["One Size"],
    fitType: "Straight",
    discountPct: 10,
    originalPrice: "₹990",
    name: "TRAVEL POUCH",
    sublabel: "Brass YKK Zipper",
    tagline: "COMPACT EVERYDAY ORGANIZER POUCH",
    imagePath: "/denim_pouch.jpg",
    price: "₹790",
    accentHex: "#0A2A5E",
    textStyle: "text-white-textured",
    btnText: "SHOP ACCESSORY →",
    btnBg: "bg-[#0A2A5E]",
    btnHover: "hover:bg-[#061c40]",
    btnTextColor: "text-white",
    shopHref: "/stores/template?category=accessories",
    categoryBadge: "ACCESSORIES",
  },
];
